//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Assignment7.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class GrantReview
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public GrantReview()
        {
            this.GrantReviewComments = new HashSet<GrantReviewComment>();
        }
    
        public int GrantReviewKey { get; set; }
        public System.DateTime GrantReviewDate { get; set; }
        public Nullable<int> GrantRequestKey { get; set; }
        public string GrantRequestStatus { get; set; }
        public Nullable<decimal> GrantAllocationAmount { get; set; }
        public Nullable<int> EmployeeKey { get; set; }
    
        public virtual Employee Employee { get; set; }
        public virtual GrantRequest GrantRequest { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<GrantReviewComment> GrantReviewComments { get; set; }
    }
}
