//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Assignment7.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class LoginHistoryTable
    {
        public int LoginHistoryKey { get; set; }
        public Nullable<int> PersonKey { get; set; }
        public System.DateTime LoginTimeStamp { get; set; }
    
        public virtual Person Person { get; set; }
    }
}
